name = "hServer Classic"
author = "Play_D"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "933a8ff75f4467683c6ccef1fe425508d8a2d5bc0042d76323f612b98010e775"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
